version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ohp
      POSTGRES_PASSWORD: ohp
      POSTGRES_DB: ohp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dev/postgres:/docker-entrypoint-initdb.d # init script
volumes:
  pgdata:
